### PR TITLE
Update ASF to v5.2.3.6 and fix errors

### PR DESCRIPTION
**Pull request by Abrynos**
Since you're stuck in a war I've taken the liberty to update ASF to version 5.2.3.6 and update the plugin accordingly.

Thank you for considering the inclusion of this merge request.

### CODE REVIEW

**Comment by woctezuma** [comment]
I have compiled the .dll file with Visual Studio 2022, and there is a small issue, I believe.

Indeed, I don't have the warning mentioned in:
- #11
However, I still have a response "unknown command" when typing the "booster" command.

**Comment by Abrynos** [comment]
This is possible in case you are running the OS specific version of ASF. If you are runnning plugins you should always use the generic version of ASF (`ASF-generic.zip`). If you look in your `log.txt` you probably can also find a `System.MissingMethodException` there at the time you executed the command.

**Comment by woctezuma** [comment]
No, I am already using the generic version of ASF.

The plugin seems to be loaded just fine, except that the `booster` command is unknown.

**Comment by woctezuma** [comment]
Is it possible that you forgot to edit these lines?

https://github.com/Ryzhehvost/BoosterCreator/blob/996f06c71f4c12baec68d07638d08b59295fb13e/BoosterCreator/Commands.cs#L17-L21

**Comment by woctezuma** [comment]
Nevermind. The issue only happens if I omit to mention the appIDs of the booster packs to craft.

**Comment by woctezuma** [comment]
Thank you for fixing the issue, @Abrynos!

If you ever have some time, it would be great if you could fix this one as well:
https://github.com/Ryzhehvost/Case-Insensitive-ASF

Otherwise, I could try to look into it, and replicate the kind of changes that you did with other plugins.

**Comment by woctezuma** [comment]
For Windows users, the compiled .DLL file can be found at:
https://github.com/woctezuma/BoosterCreator/releases/download/Fixed/BoosterCreator.dll

**Comment by Ryzhehvost** [comment]
Haven't properly reviewed the code, but I trust in your expertise. Thank you for all your help.

**Pull request merged**
